M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu20.04.1} date mer. 21 janv. 2026 02:01:50
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-21T02:01:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X4.06Y-2.08
X4.46Y-6.07
X7.17Y-6.03
X7.62Y-2.06
M30
